extends:
  - eslint:recommended
  - google
parserOptions:
  ecmaVersion: 6
env:
  node: true
globals:
  Promise: true
rules:
  object-curly-spacing:
    - error
    - always
  comma-dangle:
    - error
    - never
  max-len: off
