sudo: false
language: node_js
node_js:
  - 10
  - 11
  - 12
cache: npm
branches:
  only:
    - master
    - /^greenkeeper/.*$/
script:
  - npm run lint
  - npm run test
after_success:
  - npm run report-coverage
  - npm run semantic-release
notifications:
  email: change
