sudo: false
language: node_js
node_js:
  - 6
  - 7
  - 8
  - 9
  - 10
cache: npm
branches:
  only:
    - master
    - /^greenkeeper/.*$/
script:
  - npm start lint
  - npm start test
after_success:
  - npm start report-coverage
  - npm start semantic-release
notifications:
  email: change
